name: coverallsPR

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      image: influxdb:1.7

    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: fetch all
        run: git fetch --prune --unshallow
      - name: start Influx docker image
        run: docker run -p 8086:8086 --detach --rm influxdb:1.7
      - name: install npm dependecies
        run: npm ci
      - name: run tests
        run: npm run ci-test
        env:   
          CI: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
